# Generated by Django 2.1.3 on 2018-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webPage_pageid', models.CharField(max_length=10)),
                ('webPage_widget', models.CharField(max_length=1024)),
                ('webPage_account_id', models.CharField(max_length=8)),
            ],
        ),
    ]
