# Generated by Django 2.1.3 on 2018-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='webPage_widget',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
